---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalgreenhouse/packer-base

inputs:
  - name: version
  - name: bosh-agent-sha
  - name: bosh-agent-zip
  - name: bosh-agent-deps-zip
  - name: ovftool-linux
  - name: stemcell-builder
  - name: ps-windows-update
  - name: base-iso
  - name: ultradefrag-zip

outputs:
  - name: bosh-windows-stemcell

run:
  path: stemcell-builder/scripts/create-vsphere-stemcell.rb

params:
  OUTPUT_DIR: replace-me
  ISO_CHECKSUM_TYPE: replace-me
  ISO_CHECKSUM: replace-me
  MEMSIZE: replace-me
  NUMVCPUS: replace-me
  REMOTE_HOST: replace-me
  REMOTE_PORT: replace-me
  REMOTE_DATASTORE: replace-me
  REMOTE_CACHE_DATASTORE: replace-me
  REMOTE_CACHE_DIRECTORY: replace-me
  REMOTE_USERNAME: replace-me
  REMOTE_PASSWORD: replace-me
  GUEST_NETWORK_ADDRESS: replace-me
  GUEST_NETWORK_MASK: replace-me
  GUEST_NETWORK_GATEWAY: replace-me
  ADMINISTRATOR_PASSWORD: replace-me
